### ISSUE TITLE
Support adding 'media:content' in feed items

### ISSUE THREAD

**Issue by Joe8Bit** [nuxt-community/feed-module#101]
I'm not sure if this is a feature request or a documentation request, but it would be great if there was a documented way of adding media images to an `<item>` tag.

If we take this simple usage example with `nuxt-content` from an example `./nuxt.config.js`:

```javascript
feed() {
    const baseUrlArticles = 'https://foo.com/blog'
    const baseLinkFeedArticles = '/'
    const feedFormats = {
      rss: { type: 'rss2', file: 'rss.xml' },
      json: { type: 'json1', file: 'feed.json' },
    }
    const { $content } = require('@nuxt/content')

    const createFeedArticles = async function (feed) {
      feed.options = {
        title: 'Foo.com Blog',
        description: 'Some description',
        link: baseUrlArticles
      }
      const articles = await $content('blog').fetch()

      articles.forEach((article) => {
        const url = `${baseUrlArticles}/${article.slug}`
        if (article.published) {
          feed.addItem({
            title: article.title,
            id: url,
            link: url
            // (1)
          })
        }
      })
    }
```

I would like to add an image or media element to the item I add to the feed with the `feed.addItem` function call. That would seem to imply the support for the `<media:content>` tag within an `<item>`.

Like this example (from [here](https://www.theguardian.com/uk/sport/rss))

```xml
<media:content width="140" url="https://i.guim.co.uk/img/media/357d1db55e1891c6c5b407dcce4916c0891bbb9a/0_67_2772_1663/master/2772.jpg?width=140&quality=85&auto=format&fit=max&s=7dc394ddddec45b6413a2f7b632131d8" />
```

Or this example (from [here](https://rss.nytimes.com/services/xml/rss/nyt/World.xml)):

```xml
<media:content height="151" medium="image" url="https://static01.nyt.com/images/2021/12/28/world/28russia-memorial01/28russia-memorial01-moth.jpg" width="151"/>
```

In an ideal world I'd do something like:

```javascript
feed.addItem({
  title: 'A title',
  id: 'https://example.com/a-title',
  link: 'https://example.com/a-title',
  media: [{
    medium: 'image',
    url: 'https://example.com/image.jpg',
    height: 151,
    width: 151
  }]
})
```
Which would render an item as:

```xml
<item>
<title>A title</title>
<link>https://example.com/a-title'</link>
<pubDate>Tue, 28 Dec 2021 13:02:50 +0000</pubDate>
<media:content height="151" medium="image" url="https://example.com/image.jpg" width="151"/>
</item>
```

Any thoughts on if this is currently possible? If not, I'd be happy to add it if the project thinks it makes sense.

**Comment by Joe8Bit** [comment]
After digging in I saw that the lib uses the `feed` npm module which supports an `image` property on a feed item. I should have read the docs more carefully! Closing the issue.

**Comment by mat-hil** [comment]
Update: It seems like the image tag is not supported in rss2, I guess it therefore forces it into an enclosure tag.

---- 

> After digging in I saw that the lib uses the `feed` npm module which supports an `image` property on a feed item. I should have read the docs more carefully! Closing the issue.

I'm having the same issue right now, and don't seem to find understand the solution.

```
        feed.addItem({
            title: post.content.title,
            id: post.content.uid,
            date: new Date(post.published_at),
            image: post.imageUrl
```

The result (rss2) is not the expected `<media:content>` tag but instead, an enclosure tag:
`<enclosure url="imageUrl" length="0" type="image/png"/>`

This, however, is not working with my Mailchimp setup.
https://mailchimp.com/help/troubleshooting-rss-in-campaigns/

Am I missing something? How did you solve it @Joe8Bit?
