### ISSUE TITLE
feed output in static folder

### ISSUE THREAD

**Issue by tcurdt** [nuxt-community/feed-module#41]
Why is the plugin writing the feeds into the `static` folder?
I would expect the files to only show up in the `dist` folder.

**Comment by manniL** [comment]
Contents from `/static` are copied over to the dist folder as well. ☺️

**Comment by tcurdt** [comment]
@manniL That might be true but is beside the point. It's writing a file into what essentially is a source (in contrast to a target) directory. Plugins should not write into `static`.

**Comment by manniL** [comment]
Good point! I'd accept a tested PR to change that behavior ☺️

**Comment by ricardogobbosouza** [comment]
@tcurdt 
I'm working on this module and it's on my list to do this as `robots-module` https://github.com/nuxt-community/robots-module/blob/master/lib/module.js#L27

**Comment by manniL** [comment]
@ricardogobbosouza be aware that you need a way to support dynamic SSR mode too. Similar goes for the robots-module I'd say.

Probably sth. like https://github.com/nuxt-community/sitemap-module/blob/dev/src/index.js#L28 could work. (But don't use hardcoded `dist`).
