### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by arctouch-arthurrolim** [nuxt-community/feed-module#59]
I wanted to have some extra fields other than the ones documented. I figured out a few by my own such as date and guid, but I still needed fields such as author and categories for each entry.
If there is already a way to set those, I could not get it right, and it is not documented I believe.

**Comment by manniL** [comment]
By using a `create function` you can use all the features from https://github.com/jpmonette/feed ☺️

**Comment by arctouch-arthurrolim** [comment]
I'm still not being able to get the author and image fields to populate, the module simply ignores those.

**Comment by manniL** [comment]
@arctouch-arthurrolim then it must be an issue of the above linked module, not the nuxt wrapper
