### ISSUE TITLE
Dynamically route

### ISSUE THREAD

**Issue by The28AWG** [nuxt-community/feed-module#61]
How to redo the module to add dynamic paths?
I took addServerMiddleware as a basis and added an express handler. But I do not understand how to cache dynamic paths. Why do we need the following code:
```js
    this.nuxt.hook('generate:done', async () => {
      const xmlGeneratePath = resolve(this.options.rootDir, join(this.options.generate.dir, feedOptions.path))

      writeFileSync(xmlGeneratePath, await feedCache.get(index))
    })
```

**Comment by manniL** [comment]
The code linked is only for static sites via `nuxt generate`
