### ISSUE TITLE
feed output is still generated before nuxt generate

### ISSUE THREAD

**Issue by miteyema** [nuxt-community/feed-module#65]
Hi

I am referring to https://github.com/nuxt-community/feed-module/pull/43.
I am using v.1.1.0 of `@nuxtjs/feed` and v2.10.1 of `nuxt`.
When I generate my app, it starts by running the `create` function and not my normal page generation.
It is also still making a `feed.xml` file in my static folder.

So I think this pull is not in a new release of this module? Is this correct? 
If so, could you please make a new release of this module so we can all enjoy this new feature?

**Comment by manniL** [comment]
Yes, the release is still pending.

**Comment by miteyema** [comment]
@manniL Thanks for your reply. 
Just to understand the approval process better, what is it that is blocking a new release? A code review? Or is there something I can help with?

**Comment by manniL** [comment]
Resolved by https://github.com/nuxt-community/feed-module/commit/1224ecc2bff295067f10b55f73bbf5a866b39e99
