### ISSUE TITLE
Example typo

### ISSUE THREAD

**Issue by Youdaman** [nuxt-community/feed-module#7]
Where you have:
```
  const posts = await axios.get('https://blog.lichter.io/posts/').data
```
Should be:
```
  const posts = (await axios.get('https://blog.lichter.io/posts/')).data
```
i.e. extra parens around the await/get so it resolves before you try accessing `.data` (as per other examples below it)

**Comment by Youdaman** [comment]
Also, that URL might not be a good example as it doesn't return JSON but rather returns a HTML page.

**Comment by manniL** [comment]
Thanks @Youdaman ☺️ 
I've changed the URLs and fixed the code

**Comment by Youdaman** [comment]
Thank you! The only other thing I'd suggest is similiar to https://github.com/nuxt-community/feed-module/issues/1 maybe add the axios require line above the usage, e.g.
```
const axios = require('axios')
const posts = await (axios.get('https://api.blog.lichter.io/posts')).data
```
That way readers can do a straight copy/paste without needing to find that issue.

**Comment by manniL** [comment]
Done 👌 
Thanks a lot for you suggestions!
