### ISSUE TITLE
Output in <pre /> tags

### ISSUE THREAD

**Issue by VadimCeretean** [nuxt-community/feed-module#71]
It is normal that feed output is in pre tags?
it's looks not good
![Screenshot from 2020-03-05 08-46-56](https://user-images.githubusercontent.com/45070098/75955140-f2967d00-5ebd-11ea-84a5-a17c33743402.png)

**Comment by manniL** [comment]
Can't reproduce. Could you provide more info?

**Comment by manniL** [comment]
Stale
