### ISSUE TITLE
There seems to be quite a lack of activity, do you guys accept new maintainers ?

### ISSUE THREAD

**Issue by decebal** [nuxt-community/feed-module#77]
I'd love to chip in as a maintainer, sort out the current issues and apparently the release pipeline/circle ci is not working either. @manniL

**Comment by manniL** [comment]
Hey Decebal 👋🏻

Thanks for reaching out! I am still active but haven't had much time to work on the feed module recently. Feel free to send in PRs and triage issues. Help is much appreciated ☺️

**Comment by decebal** [comment]
thanks @manniL , much appreciated, I will get straight to it. 🚀
